### ISSUE TITLE
cannot import name 'EndTriggerEvent' from 'dirigera.devices.scene' after updating to newest version

### ISSUE THREAD

**Issue by M1lk4fr3553r** [sanjoyg/dirigera_platform#115]
After updating to the newest version the integration is no longer able to import EndTriggerEvent for me.

```
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 11:34:15 (1 occurrences)
Last logged: 11:34:15

Setup failed for custom integration 'dirigera_platform': Unable to import component: cannot import name 'EndTriggerEvent' from 'dirigera.devices.scene' (/config/deps/lib/python3.12/site-packages/dirigera/devices/scene.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dirigera_platform/__init__.py", line 10, in <module>
    from .ikea_gateway import ikea_gateway
  File "/config/custom_components/dirigera_platform/ikea_gateway.py", line 18, in <module>
    from dirigera.devices.scene import Trigger, TriggerDetails, EndTriggerEvent
ImportError: cannot import name 'EndTriggerEvent' from 'dirigera.devices.scene' (/config/deps/lib/python3.12/site-packages/dirigera/devices/scene.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dirigera_platform/__init__.py", line 10, in <module>
    from .ikea_gateway import ikea_gateway
  File "/config/custom_components/dirigera_platform/ikea_gateway.py", line 18, in <module>
    from dirigera.devices.scene import Trigger, TriggerDetails, EndTriggerEvent
ImportError: cannot import name 'EndTriggerEvent' from 'dirigera.devices.scene' (/config/deps/lib/python3.12/site-packages/dirigera/devices/scene.py)
```

**Comment by M1lk4fr3553r** [comment]
Solved by nuking python dependencies.

duplicate of #95
