### ISSUE TITLE
zigbee motion sensor error in HA when connected to DIRIGERA

### ISSUE THREAD

**Issue by Pumawave4** [sanjoyg/dirigera_platform#122]
Logger: homeassistant.config_entries
Bron: config_entries.py:635
Eerst voorgekomen: 9 december 2024 om 18:58:06 (5 gebeurtenissen)
Laatst gelogd: 10:45:16
Error setting up entry IKEA Dirigera Hub : 192.168.0.149 for dirigera_platform

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dirigera_platform/__init__.py", line 200, in async_setup_entry
    await platform.make_devices(hass,hass_data[CONF_IP_ADDRESS], hass_data[CONF_TOKEN])
  File "/config/custom_components/dirigera_platform/ikea_gateway.py", line 97, in make_devices
    motion_sensors = await hass.async_add_executor_job(hub.get_motion_sensors)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/hub/hub.py", line 256, in get_motion_sensors
    return [dict_to_motion_sensor(sensor, self) for sensor in sensors]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/devices/motion_sensor.py", line 34, in dict_to_motion_sensor
    return MotionSensor(dirigeraClient=dirigera_client, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MotionSensor
attributes -> isOn
  field required (type=value_error.missing)

**Comment by sanjoyg** [comment]
Can you please dump json and send to me.

**Comment by jpmurray** [comment]
I'm having the smae problem, but I think it's the hub that's causing this. I'm trying to add a Zigbee presence sensor, and Dirigera sees it as an outlet, which probably cause this ?

**Comment by sanjoyg** [comment]
That is correct. Can you dump json for me

**Comment by jpmurray** [comment]
I'm fairly new to HA, and I'm just not sure what you mean by dumping the json (I mean, I understand the words, I just don't see what to dump and where).

**Comment by sanjoyg** [comment]
The instructions are there in readme on home page
