### ISSUE TITLE
Vindstyrka Enviroment Sensor broken

### ISSUE THREAD

**Issue by acces90** [sanjoyg/dirigera_platform#31]
with the newest version of this addon my enviroment sensor is broken

here the logs:

```
2024-04-11 21:05:34.571 ERROR (MainThread) [custom_components.dirigera_platform] error encountered running update on : Luftsensor
2024-04-11 21:05:34.571 ERROR (MainThread) [custom_components.dirigera_platform] 'ikea_vindstyrka_device' object has no attribute 'hass'
2024-04-11 21:05:34.571 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.luftsensor_temperature fails
Traceback (most recent call last):
  File "/config/custom_components/dirigera_platform/sensor.py", line 93, in async_update
    self._json_data = await self.hass.async_add_executor_job(self._hub.get_environment_sensor_by_id, self._json_data.id)
                            ^^^^^^^^^
AttributeError: 'ikea_vindstyrka_device' object has no attribute 'hass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 175, in async_update
    await self._ikea_env_device.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 100, in async_update
    raise HomeAssistantError(ex, DOMAIN, "hub_exception")
homeassistant.exceptions.HomeAssistantError: (AttributeError("'ikea_vindstyrka_device' object has no attribute 'hass'"), 'dirigera_platform', 'hub_exception')
2024-04-11 21:05:34.574 ERROR (MainThread) [custom_components.dirigera_platform] error encountered running update on : Luftsensor
2024-04-11 21:05:34.574 ERROR (MainThread) [custom_components.dirigera_platform] 'ikea_vindstyrka_device' object has no attribute 'hass'
2024-04-11 21:05:34.575 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.luftsensor_humidity fails
Traceback (most recent call last):
  File "/config/custom_components/dirigera_platform/sensor.py", line 93, in async_update
    self._json_data = await self.hass.async_add_executor_job(self._hub.get_environment_sensor_by_id, self._json_data.id)
                            ^^^^^^^^^
AttributeError: 'ikea_vindstyrka_device' object has no attribute 'hass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 175, in async_update
    await self._ikea_env_device.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 100, in async_update
    raise HomeAssistantError(ex, DOMAIN, "hub_exception")
homeassistant.exceptions.HomeAssistantError: (AttributeError("'ikea_vindstyrka_device' object has no attribute 'hass'"), 'dirigera_platform', 'hub_exception')
2024-04-11 21:05:34.576 ERROR (MainThread) [custom_components.dirigera_platform] error encountered running update on : Luftsensor
2024-04-11 21:05:34.576 ERROR (MainThread) [custom_components.dirigera_platform] 'ikea_vindstyrka_device' object has no attribute 'hass'
2024-04-11 21:05:34.576 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.luftsensor_current_pm2_5 fails
Traceback (most recent call last):
  File "/config/custom_components/dirigera_platform/sensor.py", line 93, in async_update
    self._json_data = await self.hass.async_add_executor_job(self._hub.get_environment_sensor_by_id, self._json_data.id)
                            ^^^^^^^^^
AttributeError: 'ikea_vindstyrka_device' object has no attribute 'hass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 175, in async_update
    await self._ikea_env_device.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 100, in async_update
    raise HomeAssistantError(ex, DOMAIN, "hub_exception")
homeassistant.exceptions.HomeAssistantError: (AttributeError("'ikea_vindstyrka_device' object has no attribute 'hass'"), 'dirigera_platform', 'hub_exception')
2024-04-11 21:05:34.578 ERROR (MainThread) [custom_components.dirigera_platform] error encountered running update on : Luftsensor
2024-04-11 21:05:34.578 ERROR (MainThread) [custom_components.dirigera_platform] 'ikea_vindstyrka_device' object has no attribute 'hass'
2024-04-11 21:05:34.578 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.luftsensor_max_measured_pm2_5 fails
Traceback (most recent call last):
  File "/config/custom_components/dirigera_platform/sensor.py", line 93, in async_update
    self._json_data = await self.hass.async_add_executor_job(self._hub.get_environment_sensor_by_id, self._json_data.id)
                            ^^^^^^^^^
AttributeError: 'ikea_vindstyrka_device' object has no attribute 'hass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 175, in async_update
    await self._ikea_env_device.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 100, in async_update
    raise HomeAssistantError(ex, DOMAIN, "hub_exception")
homeassistant.exceptions.HomeAssistantError: (AttributeError("'ikea_vindstyrka_device' object has no attribute 'hass'"), 'dirigera_platform', 'hub_exception')
2024-04-11 21:05:34.579 ERROR (MainThread) [custom_components.dirigera_platform] error encountered running update on : Luftsensor
2024-04-11 21:05:34.580 ERROR (MainThread) [custom_components.dirigera_platform] 'ikea_vindstyrka_device' object has no attribute 'hass'
2024-04-11 21:05:34.580 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.luftsensor_min_measured_pm2_5 fails
Traceback (most recent call last):
  File "/config/custom_components/dirigera_platform/sensor.py", line 93, in async_update
    self._json_data = await self.hass.async_add_executor_job(self._hub.get_environment_sensor_by_id, self._json_data.id)
                            ^^^^^^^^^
AttributeError: 'ikea_vindstyrka_device' object has no attribute 'hass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 175, in async_update
    await self._ikea_env_device.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 100, in async_update
    raise HomeAssistantError(ex, DOMAIN, "hub_exception")
homeassistant.exceptions.HomeAssistantError: (AttributeError("'ikea_vindstyrka_device' object has no attribute 'hass'"), 'dirigera_platform', 'hub_exception')
2024-04-11 21:05:34.581 ERROR (MainThread) [custom_components.dirigera_platform] error encountered running update on : Luftsensor
2024-04-11 21:05:34.581 ERROR (MainThread) [custom_components.dirigera_platform] 'ikea_vindstyrka_device' object has no attribute 'hass'
2024-04-11 21:05:34.581 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.luftsensor_voc_index fails
Traceback (most recent call last):
  File "/config/custom_components/dirigera_platform/sensor.py", line 93, in async_update
    self._json_data = await self.hass.async_add_executor_job(self._hub.get_environment_sensor_by_id, self._json_data.id)
                            ^^^^^^^^^
AttributeError: 'ikea_vindstyrka_device' object has no attribute 'hass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 175, in async_update
    await self._ikea_env_device.async_update()
  File "/config/custom_components/dirigera_platform/sensor.py", line 100, in async_update
    raise HomeAssistantError(ex, DOMAIN, "hub_exception")
homeassistant.exceptions.HomeAssistantError: (AttributeError("'ikea_vindstyrka_device' object has no attribute 'hass'"), 'dirigera_platform', 'hub_exception')
```

**Comment by vulcanoid1975** [comment]
Hi,

I have 5 of those, and have no similar issue:
![image](https://github.com/sanjoyg/dirigera_platform/assets/157279185/db5a8f84-7b8e-45dc-a237-5315249d60c9)

![image](https://github.com/sanjoyg/dirigera_platform/assets/157279185/8e53429c-30a9-4b21-b828-bebc85d04ee3)

Just did an update on the integration as per @sanjoyg 's launch ...

**Comment by acces90** [comment]
mhhh weird. I just reinstalled the addon and suddenly it works. 

Before that I tried restarting HA several times without success...

**Comment by acces90** [comment]
Nah, same thing, worked for like 1 minute and then same logs as above

**Comment by vulcanoid1975** [comment]
I reloaded the integration after update (which need the restart anyway) ... that's it ... All devices work as they were ...

**Comment by sanjoyg** [comment]
Still getting the issue?

**Comment by acces90** [comment]
yep, it gets the first values when initializing i guess and then the errors in logs occure. I have the same firmware as @vulcanoid1975. The device itself is okay, it works in Ikea Home Smart app

**Comment by sanjoyg** [comment]
Let me check this

**Comment by vulcanoid1975** [comment]
Just to confirm @acces90 report:

![image](https://github.com/sanjoyg/dirigera_platform/assets/157279185/02e39357-f3d3-4853-ae93-c88bbabf1ec6)

The sensors are not updating ... 

@acces90 sorry my post was misleading, it seems the sensors only update after a reboot or reload of the integration.

Just reloaded the integration and:

![image](https://github.com/sanjoyg/dirigera_platform/assets/157279185/8b6a6efe-90b4-4962-a2ae-a69165072cf6)

**Comment by sanjoyg** [comment]
This is fixed, there was a code bug. Was introduced during the async implementation

**Comment by acces90** [comment]
there are no errors in logs appearing and in the logs I see that it pulls the actual values of my sensors (both environment sensor and the pm25 from air purifier) but those values are not updated for the entities. I'm positive it's not my HA because my other non-IKEA sensors update their values.

**Comment by vulcanoid1975** [comment]
I'll second that ... 
![image](https://github.com/sanjoyg/dirigera_platform/assets/157279185/3408f680-56b9-4adc-8140-1e3035db7801)
![image](https://github.com/sanjoyg/dirigera_platform/assets/157279185/2ffcaa97-b8a3-42b5-b0b1-f880725e8bd2)

**Comment by sanjoyg** [comment]
It seems the changes in the sensor is not pushed to hub thus to the component. Reverted to local polling, should work now please let know

**Comment by sanjoyg** [comment]
While you check this, could you also test the motion sensor if that works

**Comment by vulcanoid1975** [comment]
Good Morning,

It seems to be working now:
![image](https://github.com/sanjoyg/dirigera_platform/assets/157279185/d2e09119-2321-48fc-9cca-83b0484f9d5e)
![image](https://github.com/sanjoyg/dirigera_platform/assets/157279185/86c3ec24-a591-47d5-8b1d-facf5e57d8a1)
![image](https://github.com/sanjoyg/dirigera_platform/assets/157279185/56f90bc0-f6fa-4c64-867a-7a31e0775b2f)

Installed the update 10 mins ago, and sensors have updated with changes to environment conditions accordingly. Logs are clean, no errors.

I don't have motion sensors from Ikea, but I was going to buy one, I'll report back probably today.

Thank You @sanjoyg!

**Comment by sanjoyg** [comment]
Perfect, please do let me know once you can check with motion sensor. Closing this for now.

**Comment by vulcanoid1975** [comment]
Just for confirmation:
![image](https://github.com/sanjoyg/dirigera_platform/assets/157279185/8c6eaf92-02b1-4f73-9de5-0c61c7136586)

I had moved the Sensor in the Bathroom and Kitchen to ZigbeetoMQTT and maintained the Sensors in the Office and Bedroom on Dirigera ... updates are further in between but that's already what happened before ...

Again, Thank you!
