### ISSUE TITLE
1.8.1: Error setting up entry IKEA Dirigera Hub 

### ISSUE THREAD

**Issue by RaHehl** [sanjoyg/dirigera_platform#76]
Hi, with the latest Version i get this error, and some Devices are missing:

Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 17:13:05 (1 Vorkommnisse)
Zuletzt protokolliert: 17:13:05

Error setting up entry IKEA Dirigera Hub : 192.168.xx.xx for dirigera_platform
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dirigera_platform/__init__.py", line 119, in async_setup_entry
    from .core.motion_sensor import ikea_motion_sensor_device
ModuleNotFoundError: No module named 'custom_components.dirigera_platform.core'

**Comment by sanjoyg** [comment]
Try release 1.8.2

**Comment by RaHehl** [comment]
@sanjoyg latest Version i can select ist 1.8.1

**Comment by sanjoyg** [comment]
See it now?

**Comment by fa-ve** [comment]
> See it now?

yes visible now

**Comment by RaHehl** [comment]
error on page /config/integrations/integration/dirigera_platform is gone

there are some in the log:

Logger: homeassistant.helpers.entity
Quelle: helpers/entity.py:942
Erstmals aufgetreten: 20:03:13 (12 Vorkommnisse)
Zuletzt protokolliert: 20:03:13

Update for sensor.energy_consumed_at_last_reset_5 fails
Update for sensor.battery_percentage_3 fails
Update for sensor.time_energy_consumed_last_updated_5 fails
Update for sensor.battery_percentage fails
Update for sensor.battery_percentage_2 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 462, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:983: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 407, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='192.168.7.83', port=8443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/dirigera_platform/base_classes.py", line 77, in async_update
    self._json_data = await self._hass.async_add_executor_job(self._get_by_id_fx, self._json_data.id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/hub/hub.py", line 229, in get_outlet_by_id
    outlet = self._get_device_data_by_id(id_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/hub/hub.py", line 158, in _get_device_data_by_id
    return self.get("/devices/" + id_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/hub/hub.py", line 112, in get
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='192.168.7.83', port=8443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/dirigera_platform/base_classes.py", line 137, in async_update
    await self._device.async_update()
  File "/config/custom_components/dirigera_platform/base_classes.py", line 81, in async_update
    raise HomeAssistantError(ex, DOMAIN, "hub_exception")
homeassistant.exceptions.HomeAssistantError: (ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='192.168.7.83', port=8443): Read timed out. (read timeout=10)")), 'dirigera_platform', 'hub_exception')

For Inspelning 2 units seems to be wrong:
![image](https://github.com/user-attachments/assets/ec97b4f2-8e0f-475c-8267-20f10f78e446)

**Comment by fa-ve** [comment]
in some of the other devices we have also errors.. not only this one

**Comment by pperle** [comment]
I have fixed the unit and device class error, please see https://github.com/sanjoyg/dirigera_platform/pull/78.

But it is not listed in the energy tab, I think this is a problem which how the sensor is created because I can also not see it in http://homeassistant.local:8123/developer-tools/statistics.

**Comment by pperle** [comment]
The sensor can now be properly displayed in the energy dashboard.

**Comment by sanjoyg** [comment]
Can you confirm that the errors are not appear post ur changes as reported by @fa-ve
