### ISSUE TITLE
Light bulbs not found; error in the log

### ISSUE THREAD

**Issue by mteutelink** [sanjoyg/dirigera_platform#8]
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:344
Integration: Light (documentation, issues)
First occurred: 19:41:39 (1 occurrences)
Last logged: 19:41:39

Error while setting up dirigera_platform platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/dirigera_platform/light.py", line 44, in async_setup_entry
    hub_lights = await hass.async_add_executor_job(hub.get_lights)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/dirigera/hub/hub.py", line 137, in get_lights
    return [dict_to_light(light, self) for light in lights]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/dirigera/devices/light.py", line 109, in dict_to_light
    return Light(
           ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Light
room
  field required (type=value_error.missing)

**Comment by mteutelink** [comment]
I tried to call the dump service, but i can't find the output. Tried the logs, but found the error above.

**Comment by mteutelink** [comment]
2024-02-28 22:46:08.164 ERROR (MainThread) [homeassistant.components.light] Error while setting up dirigera_platform platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/dirigera_platform/light.py", line 44, in async_setup_entry
hub_lights = await hass.async_add_executor_job(hub.get_lights)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/deps/lib/python3.12/site-packages/dirigera/hub/hub.py", line 137, in get_lights
return [dict_to_light(light, self) for light in lights]
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/deps/lib/python3.12/site-packages/dirigera/devices/light.py", line 109, in dict_to_light
return Light(
^^^^^^
File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 341, in __init__
raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Light
room
field required (type=value_error.missing)
2024-02-28 22:46:08.610 DEBUG (MainThread) [custom_components.dirigera_platform] Found 0 env devices to setup...
2024-02-28 22:46:08.610 DEBUG (MainThread) [custom_components.dirigera_platform] Found 0 env entities to setup...
2024-02-28 22:46:08.611 DEBUG (MainThread) [custom_components.dirigera_platform] EnvSensor & Controllers Complete async_setup_entry
2024-02-28 22:46:08.656 DEBUG (MainThread) [custom_components.dirigera_platform] Found 0 motion_sensor entities to setup...
2024-02-28 22:46:08.656 DEBUG (MainThread) [custom_components.dirigera_platform] Found 0 open close entities to setup...
2024-02-28 22:46:08.656 DEBUG (MainThread) [custom_components.dirigera_platform] Binary Sensor Complete async_setup_entry
2024-02-28 22:46:38.129 DEBUG (SyncWorker_24) [custom_components.dirigera_platform] outlet update...
2024-02-28 22:46:51.888 INFO (SyncWorker_5) [custom_components.dirigera_platform] === START Devices JSON ===
2024-02-28 22:46:51.889 INFO (SyncWorker_5) [custom_components.dirigera_platform] --------------

**Comment by sanjoyg** [comment]
As you would see in the logs there are no devices that it could read from the hub. Possibly the hub was not setup correctly with the integration. The JSON dump is nothing

2024-02-28 22:46:51.888 INFO (SyncWorker_5) [custom_components.dirigera_platform] === START Devices JSON ===
2024-02-28 22:46:51.889 INFO (SyncWorker_5) [custom_components.dirigera_platform] --------------

**Comment by mteutelink** [comment]
Funny, the light bulbs work fine in IKEA Smart Home and Apple Homekit, but they don't show up in this integration.
