### ISSUE TITLE
After Update devices not reachable

### ISSUE THREAD

**Issue by DieBreuers** [sanjoyg/dirigera_platform#91]
After Update  got this Messsage:
Fehler beim Einrichten: 
Überprüfe die Protokolle

All devices don't work anymore!

The entities got some Information, too:
Battery Percentage
Diese Entität wird nicht mehr von der Integration dirigera_platform bereitgestellt. Wenn die Entität nicht mehr verwendet wird, lösche sie in den Einstellungen.

Here is the Info of the Log File.:

Logger: homeassistant.config_entries
Quelle: config_entries.py:594 
Erstmals aufgetreten: 21:11:26 (3 Vorkommnisse) 
Zuletzt protokolliert: 21:16:48

Error setting up entry IKEA Dirigera Hub : 192.168.178.122 for dirigera_platform
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dirigera_platform/__init__.py", line 118, in async_setup_entry
    await platform.make_devices(hass,hass_data[CONF_IP_ADDRESS], hass_data[CONF_TOKEN])
  File "/config/custom_components/dirigera_platform/ikea_gateway.py", line 48, in make_devices
    scenes = await hass.async_add_executor_job(hub.get_scenes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/hub/hub.py", line 337, in get_scenes
    return [dict_to_scene(scene, self) for scene in scenes]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/devices/scene.py", line 148, in dict_to_scene
    return Scene(dirigeraClient=dirigera_client, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Scene
commands -> 0
  str type expected (type=type_error.str)

**Comment by sanjoyg** [comment]
Would u enable debug and paste

**Comment by sanjoyg** [comment]
Do remove the integration/hub from hass and then add it again. This JSON is
working in my test installation

**Comment by jgoedtke** [comment]
Same here

**Comment by jgoedtke** [comment]
2024-10-18 13:05:47.531 DEBUG (MainThread) [custom_components.dirigera_platform] Starting make_devices...
2024-10-18 13:05:47.840 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry IKEA Dirigera Hub : 192.168.178.140 for dirigera_platform
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dirigera_platform/__init__.py", line 117, in async_setup_entry
    await platform.make_devices(hass,hass_data[CONF_IP_ADDRESS], hass_data[CONF_TOKEN])
  File "/config/custom_components/dirigera_platform/ikea_gateway.py", line 48, in make_devices
    scenes = await hass.async_add_executor_job(hub.get_scenes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/hub/hub.py", line 337, in get_scenes
    return [dict_to_scene(scene, self) for scene in scenes]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/devices/scene.py", line 148, in dict_to_scene
    return Scene(dirigeraClient=dirigera_client, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Scene
commands -> 0
  str type expected (type=type_error.str)
2024-10-18 13:05:47.919 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_ALBUM was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.ALBUM instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.920 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_ARTIST was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.ARTIST instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.921 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_DIRECTORY was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.DIRECTORY instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.922 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_MUSIC was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.MUSIC instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.923 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_PLAYLIST was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.PLAYLIST instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.925 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_TRACK was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.TRACK instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.926 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_TYPE_ALBUM was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.ALBUM instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.927 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_TYPE_ARTIST was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.ARTIST instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.929 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_TYPE_PLAYLIST was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.PLAYLIST instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.930 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_TYPE_TRACK was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.TRACK instead, please report it to the author of the 'mass' custom integration

**Comment by Leave-MeAlone** [comment]
This is comming from a other integration: https://github.com/music-assistant/hass-music-assistant

2024-10-18 13:05:47.919 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_ALBUM was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.ALBUM instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.920 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_ARTIST was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.ARTIST instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.921 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_DIRECTORY was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.DIRECTORY instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.922 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_MUSIC was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.MUSIC instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.923 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_PLAYLIST was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.PLAYLIST instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.925 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_CLASS_TRACK was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.TRACK instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.926 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_TYPE_ALBUM was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.ALBUM instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.927 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_TYPE_ARTIST was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.ARTIST instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.929 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_TYPE_PLAYLIST was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.PLAYLIST instead, please report it to the author of the 'mass' custom integration
2024-10-18 13:05:47.930 WARNING (ImportExecutor_0) [homeassistant.components.media_player.const] MEDIA_TYPE_TRACK was used from mass, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.TRACK instead, please report it to the author of the 'mass' custom integration

**Comment by jgoedtke** [comment]
sorry, only the lower part, changed it

**Comment by sanjoyg** [comment]
IS there still an issue?

**Comment by jgoedtke** [comment]
Yes, reconfiguring with adding the IP and 'pressing the button' on the hub is possible, but then no entity is reachable.

**Comment by sanjoyg** [comment]
any debug logs...

**Comment by jgoedtke** [comment]
Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 13:44:46 (1 Vorkommnisse)
Zuletzt protokolliert: 13:44:46

Error setting up entry IKEA Dirigera Hub : 192.168.178.140 for dirigera_platform
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dirigera_platform/__init__.py", line 117, in async_setup_entry
    await platform.make_devices(hass,hass_data[CONF_IP_ADDRESS], hass_data[CONF_TOKEN])
  File "/config/custom_components/dirigera_platform/ikea_gateway.py", line 48, in make_devices
    scenes = await hass.async_add_executor_job(hub.get_scenes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/hub/hub.py", line 337, in get_scenes
    return [dict_to_scene(scene, self) for scene in scenes]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dirigera/devices/scene.py", line 148, in dict_to_scene
    return Scene(dirigeraClient=dirigera_client, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Scene
commands -> 0
  str type expected (type=type_error.str)

**Comment by vvbasti** [comment]
Hy, the same )-;

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/dirigera_platform/__init__.py", line 117, in async_setup_entry
await platform.make_devices(hass,hass_data[CONF_IP_ADDRESS], hass_data[CONF_TOKEN])
File "/config/custom_components/dirigera_platform/ikea_gateway.py", line 48, in make_devices
scenes = await hass.async_add_executor_job(hub.get_scenes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/dirigera/hub/hub.py", line 337, in get_scenes
return [dict_to_scene(scene, self) for scene in scenes]
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/dirigera/devices/scene.py", line 148, in dict_to_scene
return Scene(dirigeraClient=dirigera_client, **data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Scene
commands -> 0
str type expected (type=type_error.str)

**Comment by sanjoyg** [comment]
Do try 2.3 please

**Comment by jgoedtke** [comment]
Looks much better, thanks for your quick support
